export const SocketEvents = {
	CONNECTED:'connect',
	DISCONNECTED:'disconnect',
	
	SET_PLAYER_ID:'SET_PLAYER_ID',
	GAME_START:'GAME_START',
	UPDATE_GAME_STATE:'UPDATE_GAME_STATE',
	JOIN_GAME_SUCCESS:'JOIN_GAME_SUCCESS',
	GAME_CLOSED:'GAME_CLOSED',
	UPDATE_IDENTITY:'UPDATE_IDENTITY',
};