version: "3"
services:
  client:
    image: node:13.6.0
    volumes:
      - .:/app
    working_dir: /app/spyfall_vue
    ports:
      - 8080:8080
    command: npm run serve
  server:
    image: node:13.6.0
    environment:
      - LOG_LEVEL=silly
      - NODE_ENV=local
    ports:
      - 4280:4280
    working_dir: /app/spyfall_server
    volumes:
      - .:/app
    command: npm start
  redis:
    image: redis:5.0.7
    # logging:
    #   driver: syslog
