version: "3"
services:
  client:
    image: node:12.18.3-alpine
    volumes:
      - .:/app
    working_dir: /app/spyfall_vue
    ports:
      - 8080:8080
    command: npm run serve
  server:
    image: node:12.18.3-alpine
    environment:
      - LOG_LEVEL=silly
      - NODE_ENV=local
    ports:
      - 4280:4280
    working_dir: /app/spyfall_server
    volumes:
      - .:/app
    command: npm start
